name: Deploy Next.js + Stripe to Azure (Zip Deployment)

on:
  push:
    branches: [ "main" ]  

env:
  AZURE_WEBAPP_NAME: omnipay        # 👈 Your Azure App Service name
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js app
      - name: Build Next.js
        env:
          STRIPE_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm run build

      # 5️⃣ Zip build + node_modules + public folder
      - name: Zip build folder
        run: zip -r app.zip .next public package.json package-lock.json node_modules

      # 6️⃣ Deploy zip to Azure
      - name: Deploy to Azure WebApp via Zip
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
